# Generated by Django 4.2.26 on 2025-12-18 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_artisan'], name='users_custo_is_arti_4a27a3_idx'),
        ),
    ]
