# Generated by Django 4.2.26 on 2025-12-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options_customuser_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='vacation_mode',
            field=models.BooleanField(default=False, help_text='Temporarily disable products from showing in the marketplace.'),
        ),
    ]
