# Generated by Django 4.2.26 on 2025-12-20 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_vacation_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtisanAccessCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Alternative password/access code', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, help_text='Who is this code for?', max_length=100)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_codes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
