# Generated by Django 4.2.26 on 2025-12-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_artisanaccesscode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Contact number for orders.', max_length=15, null=True),
        ),
    ]
