# Generated by Django 4.2.26 on 2025-12-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_artisanaccesscode'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisanaccesscode',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('MSG', 'Msg Sent'), ('INTERESTED', 'Interested'), ('DONE', 'Done')], default='NEW', max_length=20),
        ),
    ]
