# Generated by Django 4.2.26 on 2025-12-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='payment_qr_code',
            field=models.ImageField(blank=True, help_text='QR Code for receiving payments.', null=True, upload_to='payment_qrs/'),
        ),
    ]
