# Generated by Django 4.2.26 on 2025-12-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_city_order_email_order_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='landmark',
            field=models.CharField(blank=True, help_text='Nearby landmark (Optional)', max_length=200),
        ),
    ]
