# Generated by Django 4.2.26 on 2025-12-21 09:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_chatinquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_gallery/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='color_name',
            field=models.CharField(blank=True, help_text='e.g. Red, Blue, Pastel Pink', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_group',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Products sharing this ID are variants of the same item'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['variant_group'], name='store_produ_variant_4d0055_idx'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product'),
        ),
    ]
