# Generated by Django 4.2.26 on 2025-12-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_productimage_product_color_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='review',
            name='customer_name',
            field=models.CharField(blank=True, help_text='Name of customer (if added manually)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='customer_photo',
            field=models.ImageField(blank=True, null=True, upload_to='review_photos/'),
        ),
    ]
