# Generated by Django 4.2.26 on 2025-12-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_review_unique_together_review_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payment_screenshots/'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAYMENT_REVIEW', 'Payment Verification Pending'), ('IN_PROGRESS', 'In Progress'), ('FINISHING', 'Finishing Touches'), ('READY', 'Ready for Shipping'), ('SHIPPED', 'Shipped'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
