# Generated by Django 4.2.26 on 2025-12-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_order_payment_screenshot_order_payment_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAYMENT_REVIEW', 'Payment Verification Pending'), ('PAYMENT_VERIFIED', 'Payment Verified/Received'), ('IN_PROGRESS', 'In Progress'), ('FINISHING', 'Finishing Touches'), ('READY', 'Ready for Shipping'), ('SHIPPED', 'Shipped'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
