# Generated by Django 4.2.26 on 2025-12-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_order_shipping_fee_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured_banner_image',
            field=models.ImageField(blank=True, help_text='Wide banner image for the deal section', null=True, upload_to='deal_banners/'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured_deal',
            field=models.BooleanField(default=False, help_text='Show as the main featured deal on homepage'),
        ),
    ]
